# .github/workflows/main.yml
name: CI & Publish NuGet package

on:
  # Trigger on version tag pushes (e.g. v1.0.0)
  push:
    tags:
      - 'v*.*.*'
  # Allow manual dispatch
  workflow_dispatch:

jobs:
  build-test:
    name: Build, Test & Pack
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET SDKs
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            8.0.x
            9.0.x

      - name: Restore Anthropic.Client
        run: dotnet restore Anthropic.Client/Anthropic.Client.csproj

      - name: Build Anthropic.Client (multi‑target)
        run: |
          dotnet build Anthropic.Client/Anthropic.Client.csproj \
            --configuration Release

      - name: Run unit tests
        run: |
          dotnet test Anthropic.Client.Tests/Anthropic.Client.Tests.csproj --configuration Release

      - name: Pack Anthropic.Client
        run: |
          dotnet pack Anthropic.Client/Anthropic.Client.csproj \
            --configuration Release \
            --output ./artifacts \
            --no-build \
            --no-restore

      - name: Upload NuGet package
        uses: actions/upload-artifact@v4
        with:
          name: nuget-artifacts
          path: ./artifacts/*.nupkg

  publish:
    name: Publish to NuGet.org
    runs-on: ubuntu-latest
    needs: build-test
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download NuGet package
        uses: actions/download-artifact@v4
        with:
          name: nuget-artifacts
          path: ./artifacts

      - name: Setup .NET SDK 9.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Push package to NuGet.org
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          dotnet nuget push "./artifacts/*.nupkg" \
            --api-key $NUGET_API_KEY \
            --source https://api.nuget.org/v3/index.json
